### PR TITLE
fix 223

### PR DESCRIPTION
**Pull request by microsarah**

### CODE REVIEW

**Comment by jshawl** [comment]
👍 good to merge but has merge conflicts - please merge upstream/master and repush

**Comment by microsarah** [comment]
😭  i'm breaking everything @jshawl 

`Found a swap file by the name "~/Desktop/fundamentals/.git/.MERGE_MSG.swp"
          owned by: sarahhallacher   dated: Thu Oct  6 16:06:48 2016`

**Comment by jshawl** [comment]
that's ok that's some vim swap file something hang tight

**Comment by jshawl** [comment]
here's how to fix @microsarah 

```
rm .git/.MERGE_MSG.swp
git status # should be nothing to commit
git merge master
git push origin fix-223
```

**Comment by microsarah** [comment]
git status shows `	modified:   07_chapter/05_lesson.md`

**Comment by jshawl** [comment]
```
$ git add .
$ git commit -m "merge branch master"
$ git push origin fix-223```

**Comment by jnappy** [comment]
resolving here: https://github.com/GA-WDI/fundamentals/pull/275

**Pull request closed without merging**
