### PR TITLE
fixes 205

### PR DESCRIPTION
**Pull request by andrewsunglaekim**

### CODE REVIEW

**Comment by microsarah** [comment]
Hey @andrewsunglaekim can you keep an eye out for things I've assigned? I'm working through fixes now and I don't want us to double our efforts

**Comment by andrewsunglaekim** [comment]
sure! my fault, did not even notice the assignee till you mentioned it. will do. that said you are assigned on most, and i'm just doing this when i find time here and there. Let me know what you want that process to look like.

**Comment by microsarah** [comment]
no prob at all! i'm still getting used to the workflow. are you able to assign yourself? if so, feel free to do so before you take on an issue. if not maybe just add a comment and tag me? let  me know if that works for you!

**Comment by jnappy** [comment]
addressed here:  https://github.com/GA-WDI/fundamentals/pull/244/files

**Pull request closed without merging**
