### PR TITLE
fix 228

### PR DESCRIPTION
**Pull request by microsarah**

### CODE REVIEW

**Comment by jshawl** [comment]
@microsarah

**Comment by microsarah** [comment]
command line says everything up-to-date @jshawl

**Comment by jshawl** [comment]
hmm I can help (fix) the pr, but you'll need to push your branch to this repository instead of your fork.

`git push upstream fix-228`

**Comment by microsarah** [comment]
it says `fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by jnappy** [comment]
see here for resolved merge conflict: https://github.com/GA-WDI/fundamentals/pull/274

closing this one

**Pull request closed without merging**
