### PR TITLE
Master

### LINKED ISSUE #187: 2.1 HTML Elements Heading vs Header
Seems like "heading" and "header" are used here interchangeably to mean "heading".  Can we standardize on "heading" in text content at least?  To me, "header" means `<header></header>`, not `<h1></h1>`, and I want to make sure we're consistent in these early lessons.

### LINKED ISSUE #190: 2.5 Instruction don't say how to open HTML
I feel like we should immediately give fundamentals users the ability to test their code, but it doesn't say anywhere in the instructions to open index.html in the browser.  How do they know they match the deliverable?

### LINKED ISSUE #192: 4.4 Semantic Elements Typo
On 2. Optimization:

"search engines like Google will have an easier time understanding the content on your *sire*,"
should say *site*

Right before "Additional Semantic Elements" section:

"While these elements provide a fundamental structure for your page, *but* they definitely lack specificity!"
get rid of *but*

### LINKED ISSUE #194: 4.4.1 Commenting outside <html> tag
This guy in the JS Bin exercise:

``

Needs to be moved inside the <html> tag.  Otherwise, it shows up in "Output", and would be really distracting/confusing for students.

### LINKED ISSUE #195: 4.7 Assignment Misleading Steps
The last of the requirements says:

"Last but surely not least, give your site a nice touch by centering all *if* its text."

Firstly, that should say *of*.
Secondly, the "Deliverable" does not have centered text, nor is this included in the "steps to complete the assignment.

Another "issue" is that we have this code on step 3:

`.name {
  color: #ff0000;
}`

Don't think we need that.  The instructions are clear enough already, and they have plenty of examples to look at.  I want to avoid the temptation to copy-and-paste solutions whenever possible.

### LINKED ISSUE #197: Short-term fixes for JS Bin
Moving this to a new issue, because we could fix these things relatively quickly.

I've found this to be true, and unsure what exactly reproduces it. Pretty sure it is navigating away and back to a JS Bin exercise:

*Problem:* Instructions say to "type your answers directly into the text editor below", but there is not a text editor. There is a link to JS Bin, and I suppose that is what is meant, but it is still not clear to me where the JS Bin editor went.

*Solution:* This can be resolved by refreshing the page. Perhaps, we just need to add a note to refresh the page if they don't see a JS Bin editor?

### LINKED ISSUE #201: 5.3.1 Unnecessary Checkpoint?
"3 . We want all headings bold. So, add a font-weight property to h1, h2 and set it to 800.

Checkpoint: Make all the headers bold by setting the font-weight to 800."

What's that checkpoint for?  Just confuses me, because there aren't any other checkpoints on the screen.

### PR DESCRIPTION
**Pull request by microsarah**
Fixes #187
Fixes #190
Fixes #192
Fixes #194 
Fixes #195
Fixes #197
Fixes #201

### CODE REVIEW

**Comment by jshawl** [comment]
@microsarah it is easier to review these changes if you create a separate pr for each fix

**Comment by microsarah** [comment]
@jshawl was just about to write you an apology for this lol. thanks for your 👀

**Comment by jshawl** [comment]
👍 radicool

**Comment by jshawl** [comment]
no need to apologize! but also always down to pair / help about git stuff

**Comment by microsarah** [comment]
thanks man! really appreciate it. definitely gonna take you up on that

**Pull request merged**
