### PR TITLE
Remove mention of instructors reviewing progress

### PR DESCRIPTION
**Pull request by jshawl**

### CODE REVIEW

**Comment by jnappy** [comment]
@jaytongsays + @sam-barrow should review this one.  Not sure what the process looks like/will look like.

**Comment by jshawl** [comment]
cc @JonRojas

**Comment by JonRojas** [comment]
@jaytongsays + @sam-barrow I agree with the new language provided:

> While most quizzes and assignments won't be formally graded, your producer will be checking your submissions to make sure you've completed Fundamentals and made all the necessary 
progress before your first week of WDI.

It makes sense to have producers check progress as instructors will more than likely be in a different cohort while their new students are working through prework.

Also, what happens if students do **not** complete Fundamentals? Currently, there is no impact on their status. (except for receiving emails from producers reminding them to complete it)

Side note: "producter" should be "producer" @jshawl (line 64)

**Comment by jshawl** [comment]
thoughts? @jaytongsays + @sam-barrow

**Comment by jaytongsays** [comment]
@jshawl thanks for this, merged now. 

@JonRojas re: completion of fundamentals, I'm speaking with boston team to see how they're mandating Fundamentals (from what I've heard). regardless, we'll need to introduce a process tweak that me and @sam-barrow will manage to bump up completion rate.

**Pull request merged**
